# .travis.yml
language: node_js

node_js:
  - 'lts/*'

branches:
  only:
    - production

before_install:
  - yarn global add gatsby-cli

install:
  - yarn install

before_script:
  - git config --global user.name JeonghunKong
  - git config --global user.email rhdtl78@gmail.com
  - sed -i "s/__GITHUB_TOKEN__/${GITHUB_TOKEN}/" _config.yml

script:
  - yarn build
