Copycopy code to clipboard
language: node_js
node_js:
  - "lts/*"
before_script:
  - yarn install -g gatsby-cli
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: production