language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules

before_install:
  - yarn global add gatsby-cli

install:
  - yarn install

script:
  - gatsby build --prefix-paths

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Travis CI에서 설정가능한 환경 변수입니다.
  local_dir: public
  on:
    branch: master
