# .travis.yml
language: node_js

node_js:
  - 'lts/*'

branches:
  only:
    - develop

before_install:
  - yarn global add gatsby-cli

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: develop
