@startuml email-crawler-order
actor EmailCrawler
participant EmailService
participant Application
actor OrderCrawler
participant SRM
database Database

autonumber
EmailCrawler -> EmailService : Monitoring Emails
EmailService --> EmailCrawler : Crawled Emails

alt new order catched
EmailCrawler -> Application : <<Event>> PurchaseOrderDeployed
Application -> OrderCrawler : Request crawl orders
OrderCrawler -> SRM : CrawlOrder
SRM --> OrderCrawler : CrawledOrderInfo
OrderCrawler --> Application : Results
Application -> Database : Save all
else no order catched
EmailCrawler -> EmailCrawler : No orders catched
end
@enduml